name: 'Production Release'

on:
  push:
    branches:
      - main

jobs:
  publish:
    permissions:
      contents: write
    runs-on: windows-latest
    # Optional: add environment gate for approval before publish
    # environment: production
    steps:
      - uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
          VITE_APTABASE_KEY: ${{ secrets.APTABASE_KEY }}
        with:
          tagName: app-v__VERSION__
          releaseName: 'VTJS v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: false
          prerelease: false
          args: ${{ matrix.args }}

      - name: Update Gist
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.TOKEN }}
          gist_id: 0b5f7094000f4063d72276c5e05824aa
          file_path: ./latest.json
          gist_file_name: 'prod.json'
