name: 'Test Release'

on:
  pull_request:
    branches:
      - test

jobs:
  test:
    permissions:
      contents: write
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          apt-get update
          apt-get install -y \
            pkg-config \
            libglib2.0-dev \
            libwebkit2gtk-4.0-dev \
            libgtk-3-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            libssl-dev \
            libdbus-1-dev \
            libudev-dev \
            libnotify-dev

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install pnpm
        run: npm i -g pnpm

      - name: Create lockfile
        run: echo '"Riot Client:1888:12345:6VCDFORUm1nbDfZ4EReVqw:https"' > lockfile.json

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Install frontend dependencies
        run: pnpm install

      - name: Check system dependencies
        run: |
          echo "=== System Dependencies Check ==="
          echo "Checking for pkg-config..."
          if command -v pkg-config >/dev/null 2>&1; then
            echo "✓ pkg-config found at: $(which pkg-config)"
            echo "pkg-config version: $(pkg-config --version)"
          else
            echo "✗ pkg-config not found"
          fi
          
          echo "Checking for glib-2.0..."
          if pkg-config --exists glib-2.0 2>/dev/null; then
            echo "✓ glib-2.0 found"
            echo "glib-2.0 version: $(pkg-config --modversion glib-2.0)"
          else
            echo "✗ glib-2.0 not found"
          fi
          
          echo "Checking for webkit2gtk-4.0..."
          if pkg-config --exists webkit2gtk-4.0 2>/dev/null; then
            echo "✓ webkit2gtk-4.0 found"
          else
            echo "✗ webkit2gtk-4.0 not found"
          fi
          
          echo "PKG_CONFIG_PATH: $PKG_CONFIG_PATH"
          echo "PATH: $PATH"
          echo "=== End Check ==="

      # - name: Run Tests
      #   run: pnpm test --run

      # - name: Run Build
      #   run: pnpm build

      - name: App build
        run: pnpm tauri build
